export const EnemyArchetypes = Object.freeze({
    normal: {
        id: 'normal',
        color: 0xff6f5a,
        speed: 0.06,
        health: 100,
        damageMultiplier: 1,
        attackRange: 2.2,
        attackCooldown: 1100,
        radius: 0.82,
        height: 1.75,
        scale: 1,
        score: 100
    },
    flanker: {
        id: 'flanker',
        color: 0x78beff,
        speed: 0.078,
        health: 85,
        damageMultiplier: 0.9,
        attackRange: 2.05,
        attackCooldown: 950,
        radius: 0.8,
        height: 1.7,
        scale: 0.96,
        score: 120,
        mediumRange: 8.5,
        strafeSwitchMin: 1.5,
        strafeSwitchMax: 3,
        closeBurstMin: 0.45,
        closeBurstMax: 0.75,
        closeBurstChancePerSec: 0.45,
        closeBurstCooldownMin: 1.5,
        closeBurstCooldownMax: 2.8,
        strafeForwardBias: 0.22,
        leanAngle: 0.22
    },
    exploder: {
        id: 'exploder',
        color: 0xff6767,
        speed: 0.045,
        health: 60,
        damageMultiplier: 0,
        attackRange: 0,
        attackCooldown: 0,
        radius: 0.86,
        height: 1.62,
        scale: 1.02,
        score: 90,
        triggerRange: 4.2,
        fuseDuration: 1.0,
        blastRadius: 6.2,
        blastDamageMultiplier: 2.6
    }
});
